url: "https://rockandrollcanada.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/daily-record" # the subpath of your site, e.g. /blog
title: "daily-record" # the name of your site, e.g. ACME Corp.
